<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Online school</title>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
</head>

<body>
<div class="main-content color1">
    <h1>Online school</h1>
</div>

<div class="menu">
    <h2>Перегляд даних по категоріям</h2>
</div>
<div class="container">
    <ul>
        <li><a href="/spring" target="_parent">Інформація про
                курси</a></li>
        <li><a href="/spring" target="_parent">Інформація
                про вчителів</a></li>
        <li><a href="/students" target="_parent">Інформація
                про студентів</a></li>
    </ul>

</div>

<hr>

<h3>Створення категорій</h3>

<div class="flex-container">
    <ul>
        <li><a href="/spring" target="_parent">Створити курс</a></li>
        <li><a href="/spring">Створити лекцію</a></li>
        <li><a href="/spring">Створити вчителя</a></li>
        <li><a href="/student">Створити студента</a></li>
        <li><a href="/spring">Створити домашнє завдання</a></li>
        <li><a href="/spring">Створити додаткові матеріали</a></li>
    </ul>
</div>

<hr>

<h3>Перегляд сортувань</h3>
<div class="flex-container">
    <ol>
        <li><a href="/spring" target="_parent">Дані про студентів
                відсортовані за прізвищем</a></li>
        <li><a href="/spring">Назва лекції та кількість додаткових
                матеріалів</a></li>
        <li><a href="/spring">Лекція створена раніше за всіх</a></li>
        <li><a href="/spring">Кількість додаткових матеріалів по
                категоріям</a></li>
        <li><a href="/spring"> Список вчителів до літери N</a></li>
        <li><a href="/spring"> Студенти за кількістю курсів</a></li>
    </ol>
</div>

<footer>
    <p>©.All rights reserved</p>
</footer>

</body>
</html>